### ISSUE TITLE
[Crash]: Server Crash [2.29]

### ISSUE THREAD

**Issue by Coolisbetter** [AllTheMods/ATM-10#1997]
### Possible Fixes

Yes

### Modpack Version

Server 2.29

### What happened?

Using `itzg/minecraft-server` docker image, configured as:
```
services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/"
      CF_API_KEY: "REDACTED"
      MEMORY: "10G"
      USE_AIKAR_FLAGS: "false"
      DIFFICULTY: "2"
    volumes:
      - "./atm10_data:/data"
```

Server crashes after a minute of uptime. Crashreport attached 

### Crash Log

https://gist.github.com/Coolisbetter/4325a4581c80d5d7ca63bbaa2bb65cfa

### Latest.Log

https://gist.github.com/Coolisbetter/8bbc290f185959be39881fa27e78fb6f
